// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.1
// source: api/digitalcallput/digitalcallput.proto

package digitalcallput

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DigitalcallputService_GetAsk_FullMethodName    = "/digitalcallput.v1.DigitalcallputService/GetAsk"
	DigitalcallputService_StreamAsk_FullMethodName = "/digitalcallput.v1.DigitalcallputService/StreamAsk"
	DigitalcallputService_GetBid_FullMethodName    = "/digitalcallput.v1.DigitalcallputService/GetBid"
	DigitalcallputService_StreamBid_FullMethodName = "/digitalcallput.v1.DigitalcallputService/StreamBid"
)

// DigitalcallputServiceClient is the client API for DigitalcallputService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DigitalcallputServiceClient interface {
	GetAsk(ctx context.Context, in *GetAskRequest, opts ...grpc.CallOption) (*GetAskResponse, error)
	StreamAsk(ctx context.Context, in *StreamAskRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetAskResponse], error)
	GetBid(ctx context.Context, in *GetBidRequest, opts ...grpc.CallOption) (*GetBidResponse, error)
	StreamBid(ctx context.Context, in *StreamBidRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetBidResponse], error)
}

type digitalcallputServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDigitalcallputServiceClient(cc grpc.ClientConnInterface) DigitalcallputServiceClient {
	return &digitalcallputServiceClient{cc}
}

func (c *digitalcallputServiceClient) GetAsk(ctx context.Context, in *GetAskRequest, opts ...grpc.CallOption) (*GetAskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAskResponse)
	err := c.cc.Invoke(ctx, DigitalcallputService_GetAsk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *digitalcallputServiceClient) StreamAsk(ctx context.Context, in *StreamAskRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetAskResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DigitalcallputService_ServiceDesc.Streams[0], DigitalcallputService_StreamAsk_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamAskRequest, GetAskResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DigitalcallputService_StreamAskClient = grpc.ServerStreamingClient[GetAskResponse]

func (c *digitalcallputServiceClient) GetBid(ctx context.Context, in *GetBidRequest, opts ...grpc.CallOption) (*GetBidResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBidResponse)
	err := c.cc.Invoke(ctx, DigitalcallputService_GetBid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *digitalcallputServiceClient) StreamBid(ctx context.Context, in *StreamBidRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetBidResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DigitalcallputService_ServiceDesc.Streams[1], DigitalcallputService_StreamBid_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamBidRequest, GetBidResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DigitalcallputService_StreamBidClient = grpc.ServerStreamingClient[GetBidResponse]

// DigitalcallputServiceServer is the server API for DigitalcallputService service.
// All implementations must embed UnimplementedDigitalcallputServiceServer
// for forward compatibility.
type DigitalcallputServiceServer interface {
	GetAsk(context.Context, *GetAskRequest) (*GetAskResponse, error)
	StreamAsk(*StreamAskRequest, grpc.ServerStreamingServer[GetAskResponse]) error
	GetBid(context.Context, *GetBidRequest) (*GetBidResponse, error)
	StreamBid(*StreamBidRequest, grpc.ServerStreamingServer[GetBidResponse]) error
	mustEmbedUnimplementedDigitalcallputServiceServer()
}

// UnimplementedDigitalcallputServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDigitalcallputServiceServer struct{}

func (UnimplementedDigitalcallputServiceServer) GetAsk(context.Context, *GetAskRequest) (*GetAskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAsk not implemented")
}
func (UnimplementedDigitalcallputServiceServer) StreamAsk(*StreamAskRequest, grpc.ServerStreamingServer[GetAskResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamAsk not implemented")
}
func (UnimplementedDigitalcallputServiceServer) GetBid(context.Context, *GetBidRequest) (*GetBidResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBid not implemented")
}
func (UnimplementedDigitalcallputServiceServer) StreamBid(*StreamBidRequest, grpc.ServerStreamingServer[GetBidResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamBid not implemented")
}
func (UnimplementedDigitalcallputServiceServer) mustEmbedUnimplementedDigitalcallputServiceServer() {}
func (UnimplementedDigitalcallputServiceServer) testEmbeddedByValue()                               {}

// UnsafeDigitalcallputServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DigitalcallputServiceServer will
// result in compilation errors.
type UnsafeDigitalcallputServiceServer interface {
	mustEmbedUnimplementedDigitalcallputServiceServer()
}

func RegisterDigitalcallputServiceServer(s grpc.ServiceRegistrar, srv DigitalcallputServiceServer) {
	// If the following call pancis, it indicates UnimplementedDigitalcallputServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DigitalcallputService_ServiceDesc, srv)
}

func _DigitalcallputService_GetAsk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DigitalcallputServiceServer).GetAsk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DigitalcallputService_GetAsk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DigitalcallputServiceServer).GetAsk(ctx, req.(*GetAskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DigitalcallputService_StreamAsk_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamAskRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DigitalcallputServiceServer).StreamAsk(m, &grpc.GenericServerStream[StreamAskRequest, GetAskResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DigitalcallputService_StreamAskServer = grpc.ServerStreamingServer[GetAskResponse]

func _DigitalcallputService_GetBid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DigitalcallputServiceServer).GetBid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DigitalcallputService_GetBid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DigitalcallputServiceServer).GetBid(ctx, req.(*GetBidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DigitalcallputService_StreamBid_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamBidRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DigitalcallputServiceServer).StreamBid(m, &grpc.GenericServerStream[StreamBidRequest, GetBidResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DigitalcallputService_StreamBidServer = grpc.ServerStreamingServer[GetBidResponse]

// DigitalcallputService_ServiceDesc is the grpc.ServiceDesc for DigitalcallputService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DigitalcallputService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "digitalcallput.v1.DigitalcallputService",
	HandlerType: (*DigitalcallputServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAsk",
			Handler:    _DigitalcallputService_GetAsk_Handler,
		},
		{
			MethodName: "GetBid",
			Handler:    _DigitalcallputService_GetBid_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamAsk",
			Handler:       _DigitalcallputService_StreamAsk_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamBid",
			Handler:       _DigitalcallputService_StreamBid_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/digitalcallput/digitalcallput.proto",
}
