// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: digitalcallput/v1/digitalcallput.proto

package digitalcallput

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DigitalCallPutService_GetAsk_FullMethodName    = "/digitalcallput.v1.DigitalCallPutService/GetAsk"
	DigitalCallPutService_StreamAsk_FullMethodName = "/digitalcallput.v1.DigitalCallPutService/StreamAsk"
	DigitalCallPutService_GetBid_FullMethodName    = "/digitalcallput.v1.DigitalCallPutService/GetBid"
	DigitalCallPutService_StreamBid_FullMethodName = "/digitalcallput.v1.DigitalCallPutService/StreamBid"
)

// DigitalCallPutServiceClient is the client API for DigitalCallPutService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Digital Call/Put Options Pricing Service
type DigitalCallPutServiceClient interface {
	// GetAsk returns a single Ask price for a proposed contract
	GetAsk(ctx context.Context, in *GetAskRequest, opts ...grpc.CallOption) (*GetAskResponse, error)
	// StreamAsk streams Ask prices as market conditions change
	StreamAsk(ctx context.Context, in *GetAskRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetAskResponse], error)
	// GetBid returns current market value of an active contract
	GetBid(ctx context.Context, in *GetBidRequest, opts ...grpc.CallOption) (*GetBidResponse, error)
	// StreamBid streams Bid prices for active contracts
	StreamBid(ctx context.Context, in *GetBidRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetBidResponse], error)
}

type digitalCallPutServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDigitalCallPutServiceClient(cc grpc.ClientConnInterface) DigitalCallPutServiceClient {
	return &digitalCallPutServiceClient{cc}
}

func (c *digitalCallPutServiceClient) GetAsk(ctx context.Context, in *GetAskRequest, opts ...grpc.CallOption) (*GetAskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAskResponse)
	err := c.cc.Invoke(ctx, DigitalCallPutService_GetAsk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *digitalCallPutServiceClient) StreamAsk(ctx context.Context, in *GetAskRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetAskResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DigitalCallPutService_ServiceDesc.Streams[0], DigitalCallPutService_StreamAsk_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetAskRequest, GetAskResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DigitalCallPutService_StreamAskClient = grpc.ServerStreamingClient[GetAskResponse]

func (c *digitalCallPutServiceClient) GetBid(ctx context.Context, in *GetBidRequest, opts ...grpc.CallOption) (*GetBidResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBidResponse)
	err := c.cc.Invoke(ctx, DigitalCallPutService_GetBid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *digitalCallPutServiceClient) StreamBid(ctx context.Context, in *GetBidRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetBidResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DigitalCallPutService_ServiceDesc.Streams[1], DigitalCallPutService_StreamBid_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetBidRequest, GetBidResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DigitalCallPutService_StreamBidClient = grpc.ServerStreamingClient[GetBidResponse]

// DigitalCallPutServiceServer is the server API for DigitalCallPutService service.
// All implementations must embed UnimplementedDigitalCallPutServiceServer
// for forward compatibility.
//
// Digital Call/Put Options Pricing Service
type DigitalCallPutServiceServer interface {
	// GetAsk returns a single Ask price for a proposed contract
	GetAsk(context.Context, *GetAskRequest) (*GetAskResponse, error)
	// StreamAsk streams Ask prices as market conditions change
	StreamAsk(*GetAskRequest, grpc.ServerStreamingServer[GetAskResponse]) error
	// GetBid returns current market value of an active contract
	GetBid(context.Context, *GetBidRequest) (*GetBidResponse, error)
	// StreamBid streams Bid prices for active contracts
	StreamBid(*GetBidRequest, grpc.ServerStreamingServer[GetBidResponse]) error
	mustEmbedUnimplementedDigitalCallPutServiceServer()
}

// UnimplementedDigitalCallPutServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDigitalCallPutServiceServer struct{}

func (UnimplementedDigitalCallPutServiceServer) GetAsk(context.Context, *GetAskRequest) (*GetAskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAsk not implemented")
}
func (UnimplementedDigitalCallPutServiceServer) StreamAsk(*GetAskRequest, grpc.ServerStreamingServer[GetAskResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamAsk not implemented")
}
func (UnimplementedDigitalCallPutServiceServer) GetBid(context.Context, *GetBidRequest) (*GetBidResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBid not implemented")
}
func (UnimplementedDigitalCallPutServiceServer) StreamBid(*GetBidRequest, grpc.ServerStreamingServer[GetBidResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamBid not implemented")
}
func (UnimplementedDigitalCallPutServiceServer) mustEmbedUnimplementedDigitalCallPutServiceServer() {}
func (UnimplementedDigitalCallPutServiceServer) testEmbeddedByValue()                               {}

// UnsafeDigitalCallPutServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DigitalCallPutServiceServer will
// result in compilation errors.
type UnsafeDigitalCallPutServiceServer interface {
	mustEmbedUnimplementedDigitalCallPutServiceServer()
}

func RegisterDigitalCallPutServiceServer(s grpc.ServiceRegistrar, srv DigitalCallPutServiceServer) {
	// If the following call pancis, it indicates UnimplementedDigitalCallPutServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DigitalCallPutService_ServiceDesc, srv)
}

func _DigitalCallPutService_GetAsk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DigitalCallPutServiceServer).GetAsk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DigitalCallPutService_GetAsk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DigitalCallPutServiceServer).GetAsk(ctx, req.(*GetAskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DigitalCallPutService_StreamAsk_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetAskRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DigitalCallPutServiceServer).StreamAsk(m, &grpc.GenericServerStream[GetAskRequest, GetAskResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DigitalCallPutService_StreamAskServer = grpc.ServerStreamingServer[GetAskResponse]

func _DigitalCallPutService_GetBid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DigitalCallPutServiceServer).GetBid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DigitalCallPutService_GetBid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DigitalCallPutServiceServer).GetBid(ctx, req.(*GetBidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DigitalCallPutService_StreamBid_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetBidRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DigitalCallPutServiceServer).StreamBid(m, &grpc.GenericServerStream[GetBidRequest, GetBidResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DigitalCallPutService_StreamBidServer = grpc.ServerStreamingServer[GetBidResponse]

// DigitalCallPutService_ServiceDesc is the grpc.ServiceDesc for DigitalCallPutService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DigitalCallPutService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "digitalcallput.v1.DigitalCallPutService",
	HandlerType: (*DigitalCallPutServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAsk",
			Handler:    _DigitalCallPutService_GetAsk_Handler,
		},
		{
			MethodName: "GetBid",
			Handler:    _DigitalCallPutService_GetBid_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamAsk",
			Handler:       _DigitalCallPutService_StreamAsk_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamBid",
			Handler:       _DigitalCallPutService_StreamBid_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "digitalcallput/v1/digitalcallput.proto",
}
