syntax = "proto3";

package digitalcallput.v1;

option go_package="github.com/regentmarkets/service-pricer-digitalcallput/api/digitalcallput";

service DigitalcallputService {
  rpc GetAsk (GetAskRequest) returns (GetAskResponse);
  rpc StreamAsk (StreamAskRequest) returns (stream GetAskResponse);
  rpc GetBid (GetBidRequest) returns (GetBidResponse);
  rpc StreamBid (StreamBidRequest) returns (stream GetBidResponse);
}

enum ContractType {
  CONTRACT_TYPE_UNSPECIFIED = 0;
  CONTRACT_TYPE_CALL = 1;
  CONTRACT_TYPE_PUT = 2;
}

message OptionParameters {
  string symbol = 1;
  ContractType contract_type = 2;
  string currency = 3;
  string duration = 4; // e.g. "1m", "30s", "5t"
  optional string barrier = 5; // Relative (+/-) or absolute. Optional.
  optional int64 start_time = 6; // Required for active contract (Bid)
  string stake = 7; // Premium paid. Required.
}

message GetAskRequest {
  OptionParameters option_parameters = 1;
  optional int64 pricing_time = 2; // Epoch time
}

message StreamAskRequest {
  OptionParameters option_parameters = 1;
  optional int64 pricing_time = 2;
}

message GetAskResponse {
  string ask_price = 1;
  string currency = 2;
  string current_spot = 3;
  int64 current_spot_time = 4;
  string payout = 5;
  Limits limits = 6;
}

message Limits {
  string max_payout = 1;
  string min_stake = 2;
}

message GetBidRequest {
  OptionParameters option_parameters = 1;
  optional int64 pricing_time = 2;
}

message StreamBidRequest {
  OptionParameters option_parameters = 1;
  optional int64 pricing_time = 2;
}

message GetBidResponse {
  string bid_price = 1;
  bool is_expired = 2;
  string current_spot = 3;
  int64 current_spot_time = 4;
  string entry_spot = 5;
  int64 entry_spot_time = 6;
  string exit_spot = 7;
  int64 exit_spot_time = 8;
  string barrier = 9;
  int64 start_time = 10;
  int64 expiry_time = 11;
  string currency = 12;
}
