// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: digitalcallput/v1/digitalcallput.proto

package digitalcallput

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PricingService_GetAsk_FullMethodName    = "/digitalcallput.v1.PricingService/GetAsk"
	PricingService_StreamAsk_FullMethodName = "/digitalcallput.v1.PricingService/StreamAsk"
	PricingService_GetBid_FullMethodName    = "/digitalcallput.v1.PricingService/GetBid"
	PricingService_StreamBid_FullMethodName = "/digitalcallput.v1.PricingService/StreamBid"
)

// PricingServiceClient is the client API for PricingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PricingService provides real-time pricing for digital call/put options
type PricingServiceClient interface {
	// GetAsk calculates a single ask price for a digital option proposal
	GetAsk(ctx context.Context, in *GetAskRequest, opts ...grpc.CallOption) (*GetAskResponse, error)
	// StreamAsk streams continuous ask price updates for a digital option proposal
	StreamAsk(ctx context.Context, in *GetAskRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetAskResponse], error)
	// GetBid calculates a single bid price for an active contract
	GetBid(ctx context.Context, in *GetBidRequest, opts ...grpc.CallOption) (*GetBidResponse, error)
	// StreamBid streams continuous bid price updates for an active contract
	StreamBid(ctx context.Context, in *GetBidRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetBidResponse], error)
}

type pricingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPricingServiceClient(cc grpc.ClientConnInterface) PricingServiceClient {
	return &pricingServiceClient{cc}
}

func (c *pricingServiceClient) GetAsk(ctx context.Context, in *GetAskRequest, opts ...grpc.CallOption) (*GetAskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAskResponse)
	err := c.cc.Invoke(ctx, PricingService_GetAsk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pricingServiceClient) StreamAsk(ctx context.Context, in *GetAskRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetAskResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PricingService_ServiceDesc.Streams[0], PricingService_StreamAsk_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetAskRequest, GetAskResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PricingService_StreamAskClient = grpc.ServerStreamingClient[GetAskResponse]

func (c *pricingServiceClient) GetBid(ctx context.Context, in *GetBidRequest, opts ...grpc.CallOption) (*GetBidResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBidResponse)
	err := c.cc.Invoke(ctx, PricingService_GetBid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pricingServiceClient) StreamBid(ctx context.Context, in *GetBidRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetBidResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PricingService_ServiceDesc.Streams[1], PricingService_StreamBid_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetBidRequest, GetBidResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PricingService_StreamBidClient = grpc.ServerStreamingClient[GetBidResponse]

// PricingServiceServer is the server API for PricingService service.
// All implementations must embed UnimplementedPricingServiceServer
// for forward compatibility.
//
// PricingService provides real-time pricing for digital call/put options
type PricingServiceServer interface {
	// GetAsk calculates a single ask price for a digital option proposal
	GetAsk(context.Context, *GetAskRequest) (*GetAskResponse, error)
	// StreamAsk streams continuous ask price updates for a digital option proposal
	StreamAsk(*GetAskRequest, grpc.ServerStreamingServer[GetAskResponse]) error
	// GetBid calculates a single bid price for an active contract
	GetBid(context.Context, *GetBidRequest) (*GetBidResponse, error)
	// StreamBid streams continuous bid price updates for an active contract
	StreamBid(*GetBidRequest, grpc.ServerStreamingServer[GetBidResponse]) error
	mustEmbedUnimplementedPricingServiceServer()
}

// UnimplementedPricingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPricingServiceServer struct{}

func (UnimplementedPricingServiceServer) GetAsk(context.Context, *GetAskRequest) (*GetAskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAsk not implemented")
}
func (UnimplementedPricingServiceServer) StreamAsk(*GetAskRequest, grpc.ServerStreamingServer[GetAskResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamAsk not implemented")
}
func (UnimplementedPricingServiceServer) GetBid(context.Context, *GetBidRequest) (*GetBidResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBid not implemented")
}
func (UnimplementedPricingServiceServer) StreamBid(*GetBidRequest, grpc.ServerStreamingServer[GetBidResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamBid not implemented")
}
func (UnimplementedPricingServiceServer) mustEmbedUnimplementedPricingServiceServer() {}
func (UnimplementedPricingServiceServer) testEmbeddedByValue()                        {}

// UnsafePricingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PricingServiceServer will
// result in compilation errors.
type UnsafePricingServiceServer interface {
	mustEmbedUnimplementedPricingServiceServer()
}

func RegisterPricingServiceServer(s grpc.ServiceRegistrar, srv PricingServiceServer) {
	// If the following call pancis, it indicates UnimplementedPricingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PricingService_ServiceDesc, srv)
}

func _PricingService_GetAsk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PricingServiceServer).GetAsk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PricingService_GetAsk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PricingServiceServer).GetAsk(ctx, req.(*GetAskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PricingService_StreamAsk_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetAskRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PricingServiceServer).StreamAsk(m, &grpc.GenericServerStream[GetAskRequest, GetAskResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PricingService_StreamAskServer = grpc.ServerStreamingServer[GetAskResponse]

func _PricingService_GetBid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PricingServiceServer).GetBid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PricingService_GetBid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PricingServiceServer).GetBid(ctx, req.(*GetBidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PricingService_StreamBid_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetBidRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PricingServiceServer).StreamBid(m, &grpc.GenericServerStream[GetBidRequest, GetBidResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PricingService_StreamBidServer = grpc.ServerStreamingServer[GetBidResponse]

// PricingService_ServiceDesc is the grpc.ServiceDesc for PricingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PricingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "digitalcallput.v1.PricingService",
	HandlerType: (*PricingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAsk",
			Handler:    _PricingService_GetAsk_Handler,
		},
		{
			MethodName: "GetBid",
			Handler:    _PricingService_GetBid_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamAsk",
			Handler:       _PricingService_StreamAsk_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamBid",
			Handler:       _PricingService_StreamBid_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "digitalcallput/v1/digitalcallput.proto",
}
