-- Create close_trade stored procedure
CREATE OR REPLACE FUNCTION close_trade(
    p_account_id VARCHAR(20),
    p_contract_id BIGINT,
    p_sell_price DECIMAL(18,6),     -- Payout amount (0 for loss)
    p_sell_ohlcs JSONB              -- Candles 11-20 generated by application
)
RETURNS TABLE (
    sell_transaction_id BIGINT,
    new_balance DECIMAL(18,2),
    sell_time TIMESTAMP WITH TIME ZONE
) AS $$
DECLARE
    v_contract RECORD;
    v_current_balance DECIMAL(18,2);
    v_new_balance DECIMAL(18,2);
    v_txn_id BIGINT;
    v_sell_time TIMESTAMP WITH TIME ZONE := NOW();
BEGIN
    -- Validate sell_price (payout) is non-negative
    IF p_sell_price < 0 THEN
        RAISE EXCEPTION 'Sell price cannot be negative: %', p_sell_price
            USING ERRCODE = 'P0003';
    END IF;

    -- Lock account
    SELECT balance INTO v_current_balance
    FROM accounts
    WHERE account_id = p_account_id
    FOR UPDATE;
    
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Account not found: %', p_account_id
            USING ERRCODE = 'P0001';
    END IF;
    
    -- Get and lock contract
    SELECT c.contract_id, c.account_id, c.sell_time
    INTO v_contract
    FROM contracts c
    WHERE c.contract_id = p_contract_id
    FOR UPDATE;
    
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Contract not found: %', p_contract_id
            USING ERRCODE = 'P0008';
    END IF;
    
    -- Verify contract belongs to account
    IF v_contract.account_id != p_account_id THEN
        RAISE EXCEPTION 'Contract does not belong to account'
            USING ERRCODE = 'P0009';
    END IF;
    
    -- Verify contract is OPEN (sell_time IS NULL)
    IF v_contract.sell_time IS NOT NULL THEN
        RAISE EXCEPTION 'Contract is already settled'
            USING ERRCODE = 'P0010';
    END IF;
    
    -- Update contract with sell details
    UPDATE contracts
    SET sell_price = p_sell_price,
        sell_time = v_sell_time,
        sell_ohlcs = p_sell_ohlcs
    WHERE contract_id = p_contract_id;
    
    -- Credit sell_price (payout) to balance
    v_new_balance := v_current_balance + p_sell_price;
    
    UPDATE accounts
    SET balance = v_new_balance, updated_at = v_sell_time
    WHERE account_id = p_account_id;
    
    -- Create SELL transaction (positive or zero amount)
    INSERT INTO transactions (account_id, type, amount, contract_id, transaction_time)
    VALUES (p_account_id, 'SELL', p_sell_price, p_contract_id, v_sell_time)
    RETURNING transaction_id INTO v_txn_id;
    
    RETURN QUERY SELECT v_txn_id, v_new_balance, v_sell_time;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION close_trade IS 'Atomic contract settlement (SELL).
Parameters:
  p_account_id - Owner account
  p_contract_id - Contract to settle
  p_sell_price - Payout amount (0 for loss, calculated by application)
  p_sell_ohlcs - Candles 11-20 as JSONB
  
Returns:
  sell_transaction_id - SELL transaction ID
  new_balance - Updated account balance
  sell_time - Settlement timestamp
  
Note: Outcome determination and payout calculation is done by the application.
The procedure only handles atomic balance update and record creation.
  
Error codes:
  P0001 - Account not found
  P0003 - Invalid sell_price (negative)
  P0008 - Contract not found
  P0009 - Contract account mismatch
  P0010 - Contract already settled';
